name: Coveralls

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Replace with your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4

      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: 1up0f1umSgk9JNetpHN9gxwFxbvlWTjeh
        run: npx coveralls < ./coverage/lcov.info
